sudo: required
language: node_js
node_js:
  - "8"

before_script:
  - npm run selenium:install
  - npm run selenium:start

script:
  - npm run eslint
  - npm run test
  - npm run gemini
  - npm run build