sudo: required
language: node_js
node_js:
  - "8"

jobs:
  include:
  - script: npm run eslint
  - script: npm run test
  - stage: regression testing
    npm run selenium:install
    npm run selenium:start
    script: sleep 5 npm run gemini
  - script: npm run build