sudo: false
language: node_js
node_js:
  - "8"

jobs:
  include:
    - stage: lint
      script: npm run eslint
    - stage: unit testing
      script: npm run test
    - stage: selenium install
      script: npm run selenium:install
    - stage: regression testing
      script: npm run selenium:start
    - stage: regression testing
      before_script: sleep 5
      script: npm run gemini
      after_script: skip
    - stage: build
      script: npm run build